### ISSUE TITLE
Just a quick thank you note

### ISSUE THREAD

**Issue by Gabriel-p** [anguswilliams91/LinearBayes#1]
Hi there! I just wanted to thank you as I had been looking for a Python implementation of Hogg, Bovy & Langs' method for some time and just now I came across this repo (which I've forked and am currently using).

Since I could not find your email address I thought I'd drop you a note here (sorry!)

Cheers,
Gabriel

**Comment by anguswilliams91** [comment]
Hi Gabriel,

I dont quite know how, but i only just saw this! Thanks for your message. I'm glad you found it useful!
